App.tsx
components/DataPreview.tsx
components/FileUploader.tsx
components/Header.tsx
components/KPIGrid.tsx
components/ProcessedTable.tsx
components/Sidebar.tsx
index.html
index.tsx
metadata.json
types.ts
utils/csvParser.ts
utils/dataProcessor.ts
